

# 1. Libraries
import streamlit as st
import pandas as pd
import altair as alt
import plotly.express as px

# 2. Page Configuration
st.set_page_config(
    page_title="US Population Dashboard",
    page_icon="🏂",
    layout="wide",
    initial_sidebar_state="expanded")

alt.themes.enable("dark")

# 3. Data Configuration
# DATOS PRUEBA (NO REALES Y HAY QUE CAMBIARLOS POR LA BASE EN SQL)
# --------------------------------------------------------------------------------------------------------------
df = pd.read_csv('/Users/pameruiz/Library/CloudStorage/OneDrive-InstitutoTecnologicoydeEstudiosSuperioresdeMonterrey/TEC/6° Semestre/Álgebra para Criptografía/data.csv')

new_rows = [
    [19, '2024-05-01', 'Adulto', 'Carlos García', '8127466283', 'Hombre', '1981-12-04', 42, 'Argentina', 'Rosario', 'Viudo', 'MPP', '', '{Tarjeta de identidad de país de origen, Pasaporte, CURP}', 'CPEUUA7623', 'Tarjeta de Residente Temporal', 1, 3, 0, 'Primaria', 'Tercero', '{Español}', '', '2023-04-01', 0, '', '', 'Caminando', 'Violencia política', 0, '', 0, '', '', 0, '', '2024-04-15', 'Matamoros', 'Estados Unidos', 0, '', 0, '', 1, 1, 'Tengo familia allá', 0, 0, '', '', 0, '', '', 0, 'Es demasiado inseguro. No tengo recursos allá.', 0, '' , '', 0, '', 0, 0, 0, 0, '', 1, '', '{Alimento, Kit de higiene, Asesoría legal}', 'Dormitorio de caballeros planta baja', '', '', '', '', '', '', 'Necesita ayuda para reintegrarse a la sociedad'],
    [20, '2024-05-12', 'Adulto', 'David Matamoros', '1234567890', 'Hombre', '1990-01-01', 34, 'Venezuela', 'Caracas', 'Soltero', 'MPP', '', '{Tarjeta de identidad de país de origen, Pasaporte}', '', 'Tarjeta de Residente Temporal', 1, 1, 1, 'Licenciatura', 'Licenciado', '{Español, Inglés}', '', '2024-04-01', 0, '', '', 'Avión', 'Búsqueda de empleo', 0, '', 0, '', '', 0, '', '2024-04-15', 'Matamoros', 'Estados Unidos', 0, '', 0, '', 1, 1, 'Tengo familia allá', 0, 0, '', '', 0, '', '', 0, 'Es demasiado inseguro. No tengo recursos allá.', 0, '' , '', 0, '', 0, 0, 0, 0, '', 1, '', '{Alimento, Kit de higiene, Asesoría legal}', 'Dormitorio de caballeros planta baja', '', '', '', 'Tiene tatuaje en el brazo izquierdo', 'Juanita Perez - 1234567890', 'Monterrey', 'Ninguna'],
    [21, '2024-05-13', 'Adulto', 'Daniela Sanchez Rojas', '9876543210', 'Mujer', '1985-03-15', 39, 'Honduras', 'Cortés', 'Casada', 'Refugiado', '', '{Tarjeta de identidad de país de origen, Pasaporte}', '', 'Tarjeta de Residente Temporal', 0, 0, 1, 'Bachillerato', 'Bachiller', '{Español, Garífona}', '', '2023-12-10', 1, 'Pareja', 'Pareja', 'Autobús', 'Huir de violencia', 1, 'Extorsión', 0, '', '', 1, 'Menos de 20,000 MX. (1,000 US)', '2023-11-20', 'Veracruz', 'México', 0, '', 1, 'Un año', 0, 0, '', 1, 1, 'Monterrey. En el refugio XYZ.', 'Me intentaron extorsionar', 0, 'No tenía pruebas.', '', 0, 'Me buscan', 1, 'Diabetes' , 'Tomo insulina', 0, '', 0, 0, 0, 0, '', 1, '', '{Alimento, Kit de higiene, Atención psicosocial}', 'Dormitorio de damas planta baja', '', '', '', 'Tiene cicatriz en la mejilla derecha', 'Ana Sofía Mendez Sanchez - 7825531936', 'CDMX', 'Ninguna'],
    [22, '2024-05-14', 'Adulto', 'Marco Manuel Alejandro Perez', '8127466283', 'Hombre', '1981-12-04', 42, 'Argentina', 'Rosario', 'Viudo', 'MPP', '', '{Tarjeta de identidad de país de origen, Pasaporte, CURP}', 'CPEUUA7623', 'Tarjeta de Residente Temporal', 1, 3, 0, 'Primaria', 'Tercero', '{Español}', '', '2023-04-01', 0, '', '', 'Caminando', 'Violencia política', 0, '', 0, '', '', 0, '', '2024-04-15', 'Matamoros', 'Estados Unidos', 0, '', 0, '', 1, 1, 'Tengo familia allá', 0, 0, '', '', 0, '', '', 0, 'Es demasiado inseguro. No tengo recursos allá.', 0, '' , '', 0, '', 0, 0, 0, 0, '', 1, '', '{Alimento, Kit de higiene, Asesoría legal}', 'Dormitorio de caballeros planta baja', '', '', '', '', '', '', 'Necesita ayuda para reintegrarse a la sociedad'],
    [23, '2024-05-15', 'Adulto', 'Timón Pumba', '1234567890', 'Hombre', '1990-01-01', 34, 'Venezuela', 'Caracas', 'Soltero', 'MPP', '', '{Tarjeta de identidad de país de origen, Pasaporte}', '', 'Tarjeta de Residente Temporal', 1, 1, 1, 'Licenciatura', 'Licenciado', '{Español, Inglés}', '', '2024-04-01', 0, '', '', 'Avión', 'Búsqueda de empleo', 0, '', 0, '', '', 0, '', '2024-04-15', 'Matamoros', 'Estados Unidos', 0, '', 0, '', 1, 1, 'Tengo familia allá', 0, 0, '', '', 0, '', '', 0, 'Es demasiado inseguro. No tengo recursos allá.', 0, '' , '', 0, '', 0, 0, 0, 0, '', 1, '', '{Alimento, Kit de higiene, Asesoría legal}', 'Dormitorio de caballeros planta baja', '', '', '', 'Tiene tatuaje en el brazo izquierdo', 'Juanita Perez - 1234567890', 'Monterrey', 'Ninguna'],
    [24, '2024-06-17', 'Adulto', 'Rapunzel', '9876543210', 'Mujer', '1985-03-15', 39, 'Honduras', 'Cortés', 'Casada', 'Refugiado', '', '{Tarjeta de identidad de país de origen, Pasaporte}', '', 'Tarjeta de Residente Temporal', 0, 0, 1, 'Bachillerato', 'Bachiller', '{Español, Garífona}', '', '2023-12-10', 1, 'Pareja', 'Pareja', 'Autobús', 'Huir de violencia', 1, 'Extorsión', 0, '', '', 1, 'Menos de 20,000 MX. (1,000 US)', '2023-11-20', 'Veracruz', 'México', 0, '', 1, 'Un año', 0, 0, '', 1, 1, 'Monterrey. En el refugio XYZ.', 'Me intentaron extorsionar', 0, 'No tenía pruebas.', '', 0, 'Me buscan', 1, 'Diabetes' , 'Tomo insulina', 0, '', 0, 0, 0, 0, '', 1, '', '{Alimento, Kit de higiene, Atención psicosocial}', 'Dormitorio de damas planta baja', '', '', '', 'Tiene cicatriz en la mejilla derecha', 'Ana Sofía Mendez Sanchez - 7825531936', 'CDMX', 'Ninguna'],
    [25, '2024-06-03', 'Niño', 'Rafael Solano', '8127466283', 'Hombre', '1981-12-04', 42, 'Argentina', 'Rosario', 'Viudo', 'MPP', '', '{Tarjeta de identidad de país de origen, Pasaporte, CURP}', 'CPEUUA7623', 'Tarjeta de Residente Temporal', 1, 3, 0, 'Primaria', 'Tercero', '{Español}', '', '2023-04-01', 0, '', '', 'Caminando', 'Violencia política', 0, '', 0, '', '', 0, '', '2024-04-15', 'Matamoros', 'Estados Unidos', 0, '', 0, '', 1, 1, 'Tengo familia allá', 0, 0, '', '', 0, '', '', 0, 'Es demasiado inseguro. No tengo recursos allá.', 0, '' , '', 0, '', 0, 0, 0, 0, '', 1, '', '{Alimento, Kit de higiene, Asesoría legal}', 'Dormitorio de caballeros planta baja', '', '', '', '', '', '', 'Necesita ayuda para reintegrarse a la sociedad'],
    [26, '2024-05-16', 'Adulto', 'Maria Fernanda Lopez', '8765432109', 'Mujer', '1987-08-23', 36, 'El Salvador', 'San Salvador', 'Soltera', 'Refugiado', '', '{Tarjeta de identidad de país de origen, Pasaporte}', '', 'Tarjeta de Residente Temporal', 1, 0, 0, 'Licenciatura', 'Licenciada', '{Español}', '', '2024-02-15', 1, 'Hermana', 'Hermana', 'Autobús', 'Violencia de género', 1, 'Amenazas de muerte', 0, '', '', 1, 'Menos de 10,000 MX. (500 US)', '2024-01-25', 'Veracruz', 'México', 0, '', 1, 'Seis meses', 0, 0, '', 1, 1, 'Monterrey. En el refugio XYZ.', 'Me intentaron secuestrar', 0, 'No tenía pruebas.', '', 0, 'Me buscan', 1, 'Asma' , 'Inhalador', 0, '', 0, 0, 0, 0, '', 1, '', '{Alimento, Kit de higiene, Atención médica}', 'Dormitorio de damas planta baja', '', '', '', 'Tiene cicatriz en la pierna derecha', 'Luisa Lopez - 9876543210', 'CDMX', 'Ninguna'],
    [27, '2024-05-17', 'Adulto', 'Jorge Martinez', '7654321098', 'Hombre', '1989-05-10', 35, 'Guatemala', 'Guatemala City', 'Casado', 'MPP', '', '{Tarjeta de identidad de país de origen, Pasaporte, CURP}', 'GTMRTZ910510', 'Tarjeta de Residente Temporal', 1, 2, 1, 'Bachillerato', 'Bachiller', '{Español, Inglés}', '', '2023-03-05', 0, '', '', 'Caminando', 'Desastres naturales', 1, 'Inundación', 0, '', '', 1, 'Menos de 50,000 MX. (2,500 US)', '2023-02-15', 'Tapachula', 'México', 0, '', 1, 'Ocho meses', 0, 0, '', 1, 1, 'Guadalajara. En el refugio ABC.', 'Mi casa fue destruida', 0, 'No tenía pruebas.', '', 0, 'Me buscan', 1, 'Hipertensión' , 'Medicamentos', 0, '', 0, 0, 0, 0, '', 1, '', '{Alimento, Kit de higiene, Atención médica}', 'Dormitorio de caballeros planta baja', '', '', '', 'Tiene tatuaje en la espalda', 'Carlos Martinez - 7654321098', 'Puebla', 'Ninguna'],
    [28, '2024-05-18', 'Adulto', 'Lucia Ramirez', '6543210987', 'Mujer', '1992-07-12', 31, 'Nicaragua', 'Managua', 'Soltera', 'Refugiado', '', '{Tarjeta de identidad de país de origen, Pasaporte}', '', 'Tarjeta de Residente Temporal', 0, 0, 1, 'Licenciatura', 'Licenciada', '{Español, Inglés}', '', '2023-11-20', 1, 'Amigo', 'Amigo', 'Autobús', 'Violencia de género', 1, 'Violación', 0, '', '', 1, 'Menos de 20,000 MX. (1,000 US)', '2023-10-30', 'Chiapas', 'México', 0, '', 1, 'Un año', 0, 0, '', 1, 1, 'Monterrey. En el refugio XYZ.', 'Me intentaron secuestrar', 0, 'No tenía pruebas.', '', 0, 'Me buscan', 1, 'Anemia' , 'Suplementos de hierro', 0, '', 0, 0, 0, 0, '', 1, '', '{Alimento, Kit de higiene, Atención psicosocial}', 'Dormitorio de damas planta baja', '', '', '', 'Tiene cicatriz en el brazo derecho', 'Ana Ramirez - 6543210987', 'CDMX', 'Ninguna'],
    [29, '2024-05-19', 'Adulto', 'Pedro Castillo', '5432109876', 'Hombre', '1983-11-05', 40, 'Colombia', 'Bogotá', 'Casado', 'MPP', '', '{Tarjeta de identidad de país de origen, Pasaporte, CURP}', 'CLMPCST831105', 'Tarjeta de Residente Temporal', 1, 2, 1, 'Licenciatura', 'Licenciado', '{Español}', '', '2024-01-10', 0, '', '', 'Avión', 'Búsqueda de empleo', 0, '', 0, '', '', 1, 'Menos de 50,000 MX. (2,500 US)', '2023-12-20', 'Guadalajara', 'México', 0, '', 1, 'Seis meses', 0, 0, '', 1, 1, 'Monterrey. En el refugio ABC.', 'Perdí mi empleo', 0, 'No tenía pruebas.', '', 0, 'Me buscan', 1, 'Gastritis' , 'Medicamentos', 0, '', 0, 0, 0, 0, '', 1, '', '{Alimento, Kit de higiene, Asesoría legal}', 'Dormitorio de caballeros planta baja', '', '', '', 'Tiene cicatriz en la pierna izquierda', 'Juan Castillo - 5432109876', 'CDMX', 'Ninguna'],
    [30, '2024-05-20', 'Adulto', 'Marta González', '4321098765', 'Mujer', '1995-09-18', 28, 'Perú', 'Lima', 'Soltera', 'Refugiado', '', '{Tarjeta de identidad de país de origen, Pasaporte}', '', 'Tarjeta de Residente Temporal', 0, 0, 1, 'Bachillerato', 'Bachiller', '{Español}', '', '2023-08-10', 1, 'Madre', 'Madre', 'Autobús', 'Violencia de género', 1, 'Abuso doméstico', 0, '', '', 1, 'Menos de 10,000 MX. (500 US)', '2023-07-20', 'Tapachula', 'México', 0, '', 1, 'Un año', 0, 0, '', 1, 1, 'Monterrey. En el refugio XYZ.', 'Me atacaron físicamente', 0, 'No tenía pruebas.', '', 0, 'Me buscan', 1, 'Depresión' , 'Antidepresivos', 0, '', 0, 0, 0, 0, '', 1, '', '{Alimento, Kit de higiene, Atención psicosocial}', 'Dormitorio de damas planta baja', '', '', '', 'Tiene cicatriz en el rostro', 'Carla González - 4321098765', 'CDMX', 'Ninguna'],
    [31, '2024-05-21', 'Niño', 'Miguel Perez', '3210987654', 'Hombre', '1978-04-02', 46, 'Bolivia', 'La Paz', 'Viudo', 'MPP', '', '{Tarjeta de identidad de país de origen, Pasaporte, CURP}', 'BOLJPR780402', 'Tarjeta de Residente Temporal', 1, 3, 0, 'Primaria', 'Cuarto', '{Español}', '', '2023-05-10', 0, '', '', 'Caminando', 'Violencia política', 0, '', 0, '', '', 1, 'Menos de 20,000 MX. (1,000 US)', '2023-04-20', 'Matamoros', 'México', 0, '', 1, 'Ocho meses', 0, 0, '', 1, 1, 'Guadalajara. En el refugio ABC.', 'Me persiguen por mis ideas políticas', 0, 'No tenía pruebas.', '', 0, 'Me buscan', 1, 'Hipertensión' , 'Medicamentos', 0, '', 0, 0, 0, 0, '', 1, '', '{Alimento, Kit de higiene, Asesoría legal}', 'Dormitorio de caballeros planta baja', '', '', '', 'Tiene cicatriz en el cuello', 'María Perez - 3210987654', 'Puebla', 'Ninguna']
]

new_df = pd.DataFrame(new_rows, columns=df.columns)
combined_df = pd.concat([df, new_df], ignore_index=True)

combined_df
# --------------------------------------------------------------------------------------------------------------

# App Layout



# Deployment








